import { createHash } from 'node:crypto';
import { access, mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { loadApiContract } from './api-contract.ts';
import { SealwrapperError } from './errors.ts';
import { loadSealLock } from './lock.ts';

const toolRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const target = '1.6.0';
const declarationRelativePath = '.seal/types/sealdice-1.6.0.d.ts';

export type TypeSyncResult = {
  contractSha256: string;
  path: string;
  runtimeVersion: string;
  sourceCommit: string;
};

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function generatedDeclaration(projectRoot: string): Promise<{ content: string; result: TypeSyncResult }> {
  const lock = await loadSealLock(projectRoot, toolRoot);
  const locked = lock.targets[target];
  const contract = await loadApiContract(toolRoot);
  const declaration = contract.declaration;
  const contractSha256 = `sha256:${createHash('sha256').update(declaration).digest('hex')}`;
  const header = [
    '/**',
    ' * Generated by sealwrapper types sync. Do not edit this managed copy.',
    ` * Target: SealDice ${target}`,
    ` * Runtime: ${locked.core.runtimeVersion}`,
    ` * Source core: ${locked.core.commit}`,
    ` * Contract: ${contractSha256}`,
    ' */',
    '',
  ].join('\n');
  const path = join(projectRoot, declarationRelativePath);
  return {
    content: `${header}${declaration}`,
    result: { contractSha256, path, runtimeVersion: locked.core.runtimeVersion, sourceCommit: locked.core.commit },
  };
}

/** Materializes the reviewed exact-target declaration under .seal/. */
export async function syncProjectTypes(projectRoot: string): Promise<TypeSyncResult> {
  const root = resolve(projectRoot);
  const generated = await generatedDeclaration(root);
  await mkdir(dirname(generated.result.path), { recursive: true });
  const temporary = `${generated.result.path}.tmp-${process.pid}`;
  await writeFile(temporary, generated.content, { mode: 0o644 });
  await rename(temporary, generated.result.path);
  return generated.result;
}

/** Reject stale, hand-edited, or absent managed declarations. */
export async function verifyProjectTypes(projectRoot: string): Promise<TypeSyncResult> {
  const root = resolve(projectRoot);
  const generated = await generatedDeclaration(root);
  if (!(await pathExists(generated.result.path))) {
    throw new SealwrapperError(`SealDice types are not synced; run sealw types sync (${declarationRelativePath})`, 2);
  }
  const actual = await readFile(generated.result.path, 'utf8');
  if (actual !== generated.content) {
    throw new SealwrapperError(`SealDice types are stale or modified; run sealw types sync (${declarationRelativePath})`, 2);
  }
  return generated.result;
}

async function loadTypeScript(): Promise<typeof import('typescript')> {
  try {
    return await import('typescript');
  } catch {
    throw new SealwrapperError('Plugin typecheck requires the TypeScript dependency bundled with sealwrapper; reinstall the locked package', 3);
  }
}

function renderDiagnostics(ts: typeof import('typescript'), diagnostics: readonly import('typescript').Diagnostic[], root: string): string {
  return diagnostics.map((diagnostic) => {
    const message = ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n');
    if (!diagnostic.file || diagnostic.start === undefined) return `TS${diagnostic.code}: ${message}`;
    const position = diagnostic.file.getLineAndCharacterOfPosition(diagnostic.start);
    return `${relative(root, diagnostic.file.fileName)}:${position.line + 1}:${position.character + 1} TS${diagnostic.code}: ${message}`;
  }).join('\n');
}

function defaultCompilerOptions(ts: typeof import('typescript')): import('typescript').CompilerOptions {
  return {
    allowImportingTsExtensions: true,
    // SealDice sources are esbuild bundles. Bundler resolution matches that
    // environment and permits normal extensionless TypeScript imports.
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    noEmit: true,
    strict: true,
    target: ts.ScriptTarget.ES2024,
    types: [],
    verbatimModuleSyntax: true,
  };
}

function projectProgram(ts: typeof import('typescript'), projectRoot: string, declaration: string) {
  const defaults = defaultCompilerOptions(ts);
  const configPath = join(projectRoot, 'tsconfig.json');
  if (ts.sys.fileExists(configPath)) {
    const config = ts.readConfigFile(configPath, ts.sys.readFile);
    if (config.error) throw new SealwrapperError(`Invalid tsconfig.json:\n${renderDiagnostics(ts, [config.error], projectRoot)}`, 2);
    const parsed = ts.parseJsonConfigFileContent(config.config, ts.sys, projectRoot, defaults, configPath);
    if (parsed.errors.length) throw new SealwrapperError(`Invalid tsconfig.json:\n${renderDiagnostics(ts, parsed.errors, projectRoot)}`, 2);
    return { fileNames: [...new Set([...parsed.fileNames, declaration])], options: { ...defaults, ...parsed.options, noEmit: true } };
  }
  const sourceDirectory = join(projectRoot, 'src');
  const sources = ts.sys.directoryExists(sourceDirectory)
    ? ts.sys.readDirectory(sourceDirectory, ['.ts', '.mts', '.cts'], undefined, ['**/*'])
    : [];
  return { fileNames: [...new Set([...sources, declaration])], options: defaults };
}

/** Typechecks plugin code against the exact host contract without emitting JS. */
export async function typecheckProject(projectRoot: string): Promise<TypeSyncResult> {
  const root = resolve(projectRoot);
  const synced = await syncProjectTypes(root);
  const ts = await loadTypeScript();
  const program = projectProgram(ts, root, synced.path);
  const compiler = ts.createProgram(program.fileNames, program.options);
  const diagnostics = ts.getPreEmitDiagnostics(compiler);
  if (diagnostics.length) throw new SealwrapperError(`Plugin TypeScript check failed:\n${renderDiagnostics(ts, diagnostics, root)}`, 1);
  return synced;
}
