import { createHash } from 'node:crypto';
import { access, readFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { loadApiContract } from './api-contract.ts';
import { configuredDefaultTarget, loadProjectConfig } from './config.ts';
import { SealwrapperError } from './errors.ts';
import { loadSealLock, lockedTarget } from './lock.ts';
import { defaultTargetId } from './pinned-target.ts';
import { writeSafeProjectFile } from './safe-path.ts';

const toolRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const declarationRelativePath = (targetId: string) => `.seal/types/sealdice-${targetId}.d.ts`;

async function resolveProjectTarget(projectRoot: string, targetId?: string): Promise<string> {
  if (targetId) return targetId;
  try { return configuredDefaultTarget(await loadProjectConfig(projectRoot)); }
  catch (error: any) { if (error?.code === 'ENOENT') return defaultTargetId; throw error; }
}

export type TypeSyncResult = {
  contractSha256: string;
  path: string;
  runtimeVersion: string;
  sourceCommit: string;
};

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function generatedDeclaration(projectRoot: string, targetId?: string): Promise<{ content: string; result: TypeSyncResult }> {
  const selectedTargetId = await resolveProjectTarget(projectRoot, targetId);
  const lock = await loadSealLock(projectRoot, toolRoot);
  const locked = lockedTarget(lock, selectedTargetId);
  const contract = await loadApiContract(toolRoot, selectedTargetId);
  const declaration = contract.declaration;
  const contractSha256 = `sha256:${createHash('sha256').update(declaration).digest('hex')}`;
  const header = [
    '/**',
    ' * Generated by sealwrapper types sync. Do not edit this managed copy.',
    ` * Target: SealDice ${selectedTargetId}`,
    ` * Runtime: ${locked.core.runtimeVersion}`,
    ` * Source core: ${locked.core.commit}`,
    ` * Contract: ${contractSha256}`,
    ' */',
    '',
  ].join('\n');
  const path = join(projectRoot, declarationRelativePath(selectedTargetId));
  return {
    content: `${header}${declaration}`,
    result: { contractSha256, path, runtimeVersion: locked.core.runtimeVersion, sourceCommit: locked.core.commit },
  };
}

/** Materializes the reviewed declaration for one configured target under .seal/. */
export async function syncProjectTypes(projectRoot: string, targetId?: string): Promise<TypeSyncResult> {
  const root = resolve(projectRoot);
  const generated = await generatedDeclaration(root, targetId);
  await writeSafeProjectFile(root, generated.result.path, generated.content, { mode: 0o644, label: 'Managed type declaration' });
  return generated.result;
}

/** Reject stale, hand-edited, or absent managed declarations. */
export async function verifyProjectTypes(projectRoot: string, targetId?: string): Promise<TypeSyncResult> {
  const root = resolve(projectRoot);
  const generated = await generatedDeclaration(root, targetId);
  if (!(await pathExists(generated.result.path))) {
    throw new SealwrapperError(`SealDice types are not synced; run sealw types sync (${generated.result.path})`, 2);
  }
  const actual = await readFile(generated.result.path, 'utf8');
  if (actual !== generated.content) {
    throw new SealwrapperError(`SealDice types are stale or modified; run sealw types sync (${generated.result.path})`, 2);
  }
  return generated.result;
}

async function loadTypeScript(): Promise<typeof import('typescript')> {
  try {
    return await import('typescript');
  } catch {
    throw new SealwrapperError('Plugin typecheck requires the TypeScript dependency bundled with sealwrapper; reinstall the locked package', 3);
  }
}

function renderDiagnostics(ts: typeof import('typescript'), diagnostics: readonly import('typescript').Diagnostic[], root: string): string {
  return diagnostics.map((diagnostic) => {
    const message = ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n');
    if (!diagnostic.file || diagnostic.start === undefined) return `TS${diagnostic.code}: ${message}`;
    const position = diagnostic.file.getLineAndCharacterOfPosition(diagnostic.start);
    return `${relative(root, diagnostic.file.fileName)}:${position.line + 1}:${position.character + 1} TS${diagnostic.code}: ${message}`;
  }).join('\n');
}

function defaultCompilerOptions(ts: typeof import('typescript')): import('typescript').CompilerOptions {
  return {
    allowImportingTsExtensions: true,
    // SealDice sources are esbuild bundles. Bundler resolution matches that
    // environment and permits normal extensionless TypeScript imports.
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    noEmit: true,
    strict: true,
    target: ts.ScriptTarget.ES2024,
    types: [],
    verbatimModuleSyntax: true,
  };
}

function projectProgram(ts: typeof import('typescript'), projectRoot: string, declaration: string) {
  const defaults = defaultCompilerOptions(ts);
  const configPath = join(projectRoot, 'tsconfig.json');
  if (ts.sys.fileExists(configPath)) {
    const config = ts.readConfigFile(configPath, ts.sys.readFile);
    if (config.error) throw new SealwrapperError(`Invalid tsconfig.json:\n${renderDiagnostics(ts, [config.error], projectRoot)}`, 2);
    const parsed = ts.parseJsonConfigFileContent(config.config, ts.sys, projectRoot, defaults, configPath);
    if (parsed.errors.length) throw new SealwrapperError(`Invalid tsconfig.json:\n${renderDiagnostics(ts, parsed.errors, projectRoot)}`, 2);
    return { fileNames: [...new Set([...parsed.fileNames, declaration])], options: { ...defaults, ...parsed.options, noEmit: true } };
  }
  const sourceDirectory = join(projectRoot, 'src');
  const sources = ts.sys.directoryExists(sourceDirectory)
    ? ts.sys.readDirectory(sourceDirectory, ['.ts', '.mts', '.cts', '.js', '.mjs', '.cjs'], undefined, ['**/*'])
    : [];
  // Projects without a tsconfig still need their JavaScript entrypoints
  // checked.  TypeScript otherwise parses them only as pass-through inputs (or
  // omits them entirely), allowing an invalid host API use to reach esbuild.
  return { fileNames: [...new Set([...sources, declaration])], options: { ...defaults, allowJs: true, checkJs: true } };
}

/** Typechecks plugin code against the selected host contract without emitting JS. */
export async function typecheckProject(projectRoot: string, targetId?: string): Promise<TypeSyncResult> {
  const root = resolve(projectRoot);
  const synced = await syncProjectTypes(root, targetId);
  const ts = await loadTypeScript();
  const program = projectProgram(ts, root, synced.path);
  const compiler = ts.createProgram(program.fileNames, program.options);
  const diagnostics = ts.getPreEmitDiagnostics(compiler);
  if (diagnostics.length) throw new SealwrapperError(`Plugin TypeScript check failed:\n${renderDiagnostics(ts, diagnostics, root)}`, 1);
  return synced;
}
