import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';

import { renderSealLock } from '../../src/lock.ts';
import { pinnedTarget } from '../../src/pinned-target.ts';
import { syncProjectTypes, typecheckProject, verifyProjectTypes } from '../../src/types.ts';

async function createProject(source: string) {
  const root = await mkdtemp(join(tmpdir(), 'sealwrapper-types-'));
  await mkdir(join(root, 'src'), { recursive: true });
  await Promise.all([
    writeFile(join(root, 'seal.lock'), renderSealLock(pinnedTarget)),
    writeFile(join(root, 'src', 'index.ts'), source),
  ]);
  return root;
}

test('types sync writes the exact 1.6.0 host contract outside the sealpack source tree', async () => {
  const root = await createProject('const result = seal.ext.newCmdExecuteResult(true);\nvoid result;\n');
  const synced = await syncProjectTypes(root);
  assert.match(synced.path, /\.seal\/types\/sealdice-1\.6\.0\.d\.ts$/);
  const declaration = await readFile(synced.path, 'utf8');
  assert.match(declaration, /Generated by sealwrapper types sync/);
  assert.match(declaration, /Target: SealDice 1\.6\.0/);
  assert.match(declaration, /Runtime: 1\.6\.0\+20260726/);
  assert.match(declaration, /declare namespace seal/);
  await assert.doesNotReject(() => verifyProjectTypes(root));
  await writeFile(synced.path, `${declaration}\n// local edit\n`);
  await assert.rejects(() => verifyProjectTypes(root), /stale or modified/);
});

test('plugin typecheck accepts the target API and rejects unknown host members', async () => {
  const root = await createProject([
    "const extension = seal.ext.new('typed-example', 'tester', '1.0.0');",
    'const command: seal.CmdItemInfo = seal.ext.newCmdItemInfo();',
    'extension.cmdMap.typed = command;',
  ].join('\n'));
  await assert.doesNotReject(() => typecheckProject(root));

  await writeFile(join(root, 'src', 'index.ts'), 'seal.thisApiDoesNotExist();\n');
  await assert.rejects(() => typecheckProject(root), /thisApiDoesNotExist/);
});
